### ISSUE TITLE
CC0 license and CLA for translations

### ISSUE THREAD

**Issue by comradekingu** [frenck/spook#314]
### What version of Spook are you using?

1

### What version of Home Assistant are you using?

1

### The problem

>By contributing translations to the Spook project, you agree that your translations are published under the CC0 (Creative Commons Zero v1.0 Universal) license, meaning you wave copyright (and any other right); making your contributed translations public domain.

That is not what CC0 does in all jurisdictions, and it isn't compatible with the previously committed work under MIT because it has a required part that isn't part of the CC0 license.

Adding a CoC to the project without asking contributors after taking contributions is also egregious, but legal.

**Comment by frenck** [comment]
Would like like me to revert your contributions? I am happy to do that if that makes you feel more comfortable?

Also, please note, this project was never MIT licensed. As a matter of fact, by using this code you've been in violation of the license already.

**Comment by comradekingu** [comment]
It is not about comfort, but the copyright of any of the contributors.
https://hosted.weblate.org/changes/?component=integration&project=spook&lang=&action=55&user=&start_date=&end_date=
It was MIT
and the bottom of https://github.com/frenck/spook is MIT

and 6.2 of https://hosted.weblate.org/legal/terms/ would make it MIT too.

**Comment by frenck** [comment]
It is not and has never been MIT. As a matter of fact, this repo never carried any OSI-approved license.

**Comment by frenck** [comment]
The message in Weblate has been adjusted.

../Frenck

**Comment by comradekingu** [comment]
Right, so you took the MIT license, filled in
`Copyright <YEAR> <COPYRIGHT HOLDER>`

and replaced

`and to permit persons to whom the Software is furnished to do so, subject to the following conditions:`
with:
`but NOT including the right to run, execute or use the Software or any executable binaries built from the source code.`
Actually selecting the MIT license for the translations is what made me miss that.
The same reason why nobody ever tries to pull a fast one with the project license is why people are more likely to contribute to it in error.

Please do remove my contributions.

**Comment by frenck** [comment]
> Right, so you took the MIT license

No, I did not. I choose the passive aggressive license for this project source code, which is an existing license. A small Google search would have learned you that.

The reason is that, I wanted to keep this open as much as possible, yet, using this is a bad idea. This is also documented extensively in the documentation along with this repository.

> Actually selecting the MIT license for the translations is what made me miss that.

I don’t think that statement is correct. The translations are published now under the CC0 license. This to comply with the requirements of Weblate Libre that explicitly states the translations need to be published under an OSI approved license.

> Please do remove my contributions.

Sure, no problem. I am currently traveling, but will pick this up when I return in a little over a week 👍
