### ISSUE TITLE
Repair: false positive Unknown services used in: ......

### ISSUE THREAD

**Issue by andyblac** [frenck/spook#626]
### What version of Spook are you using?

2.2.2

### What version of Home Assistant are you using?

Core: 2024.2.2

### The problem

getting this in system repairs for this Blue Print `Low Battery Notification`, I have contacted the author and he says the blue print is correct, and using documented code.
<img width="624" alt="Screenshot 2024-02-16 at 10 34 10" src="https://github.com/frenck/spook/assets/77936/0a391cfc-a12d-4cd2-91e0-056650d3b5c9">

**Comment by frenck** [comment]
Do you use the todo integration?

**Comment by andyblac** [comment]
no, I do need need it

**Comment by NodeJSmith** [comment]
After updating spook yesterday I'm getting a false positive regarding androidtv.adb_command. Happy to open a separate issue but I'm wondering if it's related to this one, based on the timing and similarity.

![Screenshot_20240217_064710_Home Assistant](https://github.com/frenck/spook/assets/8505845/55660cc6-7a57-4396-b7ad-662cb7edfabb)

**Comment by frenck** [comment]
I think it is related to the issue reported that errors aren't cleaned up. Even if it was a timing issue, it should resolve normally.

**Comment by HaraldGithub** [comment]
> I think it is related to the issue reported that errors aren't cleaned up. Even if it was a timing issue, it should resolve normally.

Hi @frenck 
Since the last Update of spook I've a similar issue:
I got this repair announcement about an unknown entity:
<img width="595" alt="image" src="https://github.com/frenck/spook/assets/90566183/82ba6bfd-3883-4f55-8f2f-6e12d9d7810d">
but in developper tools this entity is known:
<img width="1010" alt="image" src="https://github.com/frenck/spook/assets/90566183/c729eedf-3302-4b03-8a02-29e161d93330">
and in "Overview" it is also available:
<img width="335" alt="image" src="https://github.com/frenck/spook/assets/90566183/90947b78-a369-4fc6-a7ea-ec8ec6916c49">
I've received this message after restart from update from 2024.2.1 to 2024.2.2.

In former times, and also before last spook-update, I've received this message, too, but it was gone some seconds after restart of HA. On restart of HA, an automation will also restart the samba-addon, so for few seconds it might be possible, that spook recognize this entity as unavailable. But after the restart of the add-on it's available (as you can see in screen shots above).
I think it's a bug in the last spook-update.

**Comment by frenck** [comment]
@HaraldGithub Please don't stack different/unrelated issues. Your message is not about services...

**Comment by HaraldGithub** [comment]
@frenck 
I know, that my problem is not related to services, but I quoted you statement, because it might be also a 
"a timing issue, it should resolve normally".
But okay, I've opened an new issue: #627

**Comment by berendhaan** [comment]
I'm having the same issue, spook doesn't seem to clean-up issues after a sensor becomes available again.

I don't think posting a screenshot will help, are there some hints in the log you could use?

**Comment by dafunkydan** [comment]
> Well the blueprint uses it, so, as a result, your automation does. Spook checks if all possible called services in an automation exists. If it doesn't, it will raise a repair.
> 
> I can see how, this is less helpful in case of a blueprint. I will check if I can learn Spook about it.

I had/have the (i guess) same Problem, where the https://github.com/lsismeiro/awesome-ha-blueprints, which i use for my Remotes, reports an empty and unknown Device
![grafik](https://github.com/frenck/spook/assets/103875104/890e6431-6881-4ae6-a7b1-650d470fa7d5)

I guess this is, because the Blueprint offers either a Field for a Controller Device (deCONZ, ZHA), or for a Controller Entity (Zigbee2MQTT), where there is always one Field empty..
